# Mysql9.xを用いたデータベースのマニフェスト
# - 名前はdb
# - データベース名はapp
# - アクセスユーザーはappuser/apppass
# - CPUは250ms、メモリは512MB上限

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:9
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
        # リソース制限
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        # 各種環境変数
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: app
        - name: MYSQL_USER
          value: appuser
        - name: MYSQL_PASSWORD
          value: apppass

  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
