apiVersion: v1
kind: Pod
metadata:
  name: mysql-and-controller
  labels:
    name: mysql-and-controller
spec:
  containers:
  - name: mysql
    image: mysql:8
    # readnessProbeを用いて、MySQLが受付可能か確認したい、execを使う
    readinessProbe:
      exec:
        command:
          - sh
          - -c
          - mysqladmin ping -u root -h 127.0.0.1 --password=$MYSQL_ROOT_PASSWORD
      periodSeconds: 10
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
  - name: controller
    image: alpine
    resources:
      limits:
        memory: "256Mi"
        cpu: "100m"
    command: ['sh', '-c', 'while true;do sleep 3600; done']
