name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install rye
      run: |
        curl -sSf https://rye.astral.sh/get | bash

    - name: Install dependencies
      run: sh -c "make init"

    - name: Run build html
      run: sh -c "make html"

